sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.000
    y: 0.000
    z: 0.000
    roll: 0.000
    pitch: 0.000
    yaw: 0.000
  velarray_front_left_base_link:
    x: 1.054
    y: 0.260
    z: -1.330
    roll: 0.000
    pitch: 0.000
    yaw: 1.047
  velarray_front_right_base_link:
    x: 1.054
    y: -0.260
    z: -1.330
    roll: 0.000
    pitch: 0.000
    yaw: -1.047
  tamagawa/imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 3.14159
    pitch: 0.0
    yaw: 0.0
